- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/ipt/NotOnIptNotInTbProgramCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/tb/MissingPyridoxineCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/IPTMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/TbMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/regimen/RegimenManager.java
- api/src/main/resources/content/kenyaemr.hiv.xml
- api/src/main/resources/content/kenyaemr.ipt.xml
- api/src/main/resources/moduleApplicationContext.xml
- api/src/main/resources/regimens.xml
- omod/src/main/webapp/resources/htmlforms/hiv/hivClinicalEncounterAddendum.html
- omod/src/main/webapp/resources/htmlforms/hiv/moh257VisitSummary.html
Fixed regimen null error on start up
fixed IPT and GeneXpert concepts and forms
> Kenyaemr v15.1.8 fixes

- omod/src/main/webapp/resources/htmlforms/clinicalEncounter.html
- omod/src/main/webapp/resources/htmlforms/hiv/hivClinicalEncounterAddendum.html
- omod/src/main/webapp/resources/htmlforms/hiv/hivFamilyHistory.html
- omod/src/main/webapp/resources/htmlforms/hiv/moh257VisitSummary.html
- omod/src/main/webapp/resources/htmlforms/labResults.html
> removed comments

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/HivMetadata.java
- api/src/main/resources/content/kenyaemr.hiv.xml
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/webapp/resources/htmlforms/hiv/hivFamilyHistory.html
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
- omod/src/main/webapp/resources/htmlforms/hiv/moh257VisitSummary.html
Initial works on a separate green card.
> Addition of separate green card and initial works

- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
> pregnancy - fp validation

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
- omod/src/main/webapp/resources/htmlforms/labResults.html
removed labs and validated tb icf skip logic
> removed labs and validated tb icf skip logic

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/wrapper/PatientWrapper.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
Added alternate phone no, email address, county drop down, nearest health facility.
Added new relationship type - partner and renamed existing to spouse to take care of existing data
> Kenya emr registration changes

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/PatientAllergiesAndChronicIllnessesFragmentController.java
- omod/src/main/webapp/fragments/patient/patientAllergiesAndChronicIllnesses.gsp
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
Corrected grouping concept for chronic illnesses,
Completed section for allergies and chronic illnesses section on patient home
> Allergies chronic illnesses section

- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
- omod/src/main/webapp/resources/htmlforms/hiv/moh257VisitSummary.html
…rophylaxis - ctx and dapsone for adherence and dispensing
> Vaidation for patient type based on existence of UPN, validation of prophylaxis - ctx and dapsone for adherence and dispensing

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/StablePatientsCalculation.java
…rd and avail ART fast track form to all stable clients in hiv program
> "Redesigned stability calculation to use reported stability in greencard and avail ART fast track form to all stable clients in hiv program"

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLMOH731GreenCardReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/shared/common/CommonDimensionLibrary.java
…card. Revised queries for Total tested +ve and total tested -ve for moh731 Greencard.
> Moh731 Greencard

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
> Removed follow up for unenrolled clients in IPT, morisky button added css

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/GreenCardVelocityCalculation.java
- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
…tatus and not ccc number availability from linkage form
> Validated enrollment form to determine patient type from enrollment status and not ccc number availability from linkage form

- api/src/main/distro/metadata/programs.xml
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/ovc/EligibleForOvcProgramCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/OTZMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/OVCMetadata.java
- api/src/main/resources/content/kenyaemr.ovc.xml
- api/src/main/resources/moduleApplicationContext.xml
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/PatientUtilsFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/ovc/OvcCarePanelFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/ovc/OvcEnrollmentSummaryFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/ovc/OvcOutcomeSummaryFragmentController.java
- omod/src/main/webapp/resources/htmlforms/ovc/ovcDiscontinuation.html
- omod/src/main/webapp/resources/htmlforms/ovc/ovcEnrollment.html
Create ovc program
Added ovc enrollment form
> Added OVC discontinuation form

- omod/src/main/webapp/resources/htmlforms/hiv/enhancedAdherenceScreening.html
> Enhanced edherence added earliestObs for Date of first session and removed mandatory requirement

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/covid/DeadCovid19CasesReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/covid/PatientsEnrolledOnQuarantineReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/covid/DeadCovid19CasesCohortDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/covid/PatientsEnrolledInQuarantineCohortDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/covid/DeadCovid19CasesCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/covid/PatientsEnrolledInQuarantineCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/covid/DateOfQuarantineAdmissionDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/covid/DeathDateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/covid/NameOfQuarantineCenterDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/covid/TransferQuarantineFacilityDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/covid/TypeOfQuarantineAdmissionDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/covid/DateOfQuarantineAdmissionDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/covid/DeathDateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/covid/NameOfQuarantineCenterDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/covid/TransferQuarantineFacilityDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/covid/TypeOfQuarantineAdmissionDataEvaluator.java
- api/src/main/resources/content/kenyaemr.common.xml
- api/src/main/resources/content/kenyaemr.covid.xml
- omod/src/main/webapp/resources/htmlforms/covid/covidOutcome.html
> Added date of death in covid outcome as a concept, added deadcovidcases linelist

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/covid/CovidDashboardCohortQueries.java
> Updated CovidDashboardCohortQueries - contacts listed and reached to join from persons table

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/covid/PatientsEnrolledOnCovidCohortDefinitionEvaluator.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/ReportPageController.java
Added provision to fetch report for all counties in the county filter dropdown.
> All counties dropdown option

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ActivePatientsSnapshotCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimCohortLibrary.java
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
- omod/src/main/webapp/resources/htmlforms/hiv/moh257VisitSummary.html
cherry picked fixes from the migration branch
> Latest migration changes

- omod/src/main/webapp/fragments/hivTesting/medicQueue.gsp
Set medic error queue entries to max 5
> Set medic error queue entries to max 5

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ActivePatientsSnapshotCohortDefinitionEvaluator.java
Updated Active on ART Patient Linelist for the <=30 days range
> Updated Active on ART Patient Linelist for the <=30 days range

- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Bug fix on htsInitial consent removed otherDisabilitySelected on run
> Bug fix on htsInitial consent removed otherDisabilitySelected

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/report/AdxViewFragmentController.java
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Added hts referral section and  removed logs
> Added hts referral section and removed logs

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Updated on ctx bug : added group by visit date so that it considers only the last visit
> Updated on ctx bug : added group by visit date

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/wrapper/PatientWrapper.java
Updated ETLMOH731 current on ART to exclude  clients who died within the period and added CHT_USERNAME in patient wrapper
> Updated ETLMOH731 current on ART to exclude  clients who died within the period and added CHT_USERNAME in patient wrapper

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimCohortLibrary.java
Updated CurrentonART for MOH371 to cater for re-enrollments, added max enrollment date
> Updated CurrentonART for MOH371 to cater for re-enrollments, added max enrollment date

- api/src/main/java/org/openmrs/module/kenyaemr/form/velocity/EmrVelocityFunctions.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
I have resolved conflicts and tested that regular UPN,  KNH UPN generation and KDOD number work seamlessly for HIV enrollment
> Added KNH autogeneration of UPN alongside KDOD Number

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/ActivePatientSnapshotReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/ETLFirstSubstitutionDateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/ETLRefillDateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/ETLStabilityDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ETLFirstSubstitutionDateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ETLRefillDateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ETLStabilityDataEvaluator.java
Added first substitution date, refill date and latest stability
> Added first substitution date, refill date and latest stability

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Bug fix on presumed tb to remove clients whose visits done by TS
> Bug fix on presumed tb to remove clients whose  visits done by TS

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Updated person_present requirement for TB screening and presumed tb
> Updated person_present requirement for TB screening and presumed tb

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/PatientAppointmentOnDayReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/ScheduledAppointmentCohortDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ScheduledAppointmentCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/HonouredAppointmentDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/HonouredAppointmentDataEvaluator.java
- api/src/main/resources/content/kenyaemr.hiv.xml
Added appointment schedule report for hiv greencard appointments on a date range
> Added appointment schedule report for hiv patients on a date range

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ETLArtStartDateDataEvaluator.java
Added date_started_art_at_transferring_facility to start art date computation
> Added date_started_art_at_transferring_facility to start art date computation 

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ActivePatientsSnapshotCohortDefinitionEvaluator.java
Updating Active On Art patient linelist to include re- enrollments
> Updating Active On Art patient linelist to include re- enrollments

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ETLLTFUWithDateRangeCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ETLLostToFollowupCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ETLMissedAppointmentsCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ETLPatientsWithSuppressedVLInLast12MonthsCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ETLPatientsWithVLInLast12MonthsCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ETLSecondLineARTCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731/ETLMoh731CohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/viralSuppression/ViralSuppressionCohortLibrary.java
Added re-enrollments for all indicators using current on ART query"
> Added re-enrollments for all indicators using current on ART query

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Updated HTS initial and retest - added setting, approach and missing Entry points and strategies plus validations
> Updated HTS initial and retest - added setting, approach and missing Entry points and strategies plus validations

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/HIVNegativePatientsCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/CCCDefaulterTracingRegisterReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/defaulterTracing/ReturnToCareDateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/defaulterTracing/ReturnToCareDateDataEvaluator.java
Added Last visit date,Last TCA Date and Return to care date colunms in
Defaulter Tracing register
> Added Last visit date,Last TCA Date and Return to care date colunms in  Defaulter Tracing register

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/resources/content/kenyaemr.common.xml
- omod/src/main/webapp/resources/htmlforms/cervicalCancerAssessment.html
- omod/src/main/webapp/resources/htmlforms/cervicalCancerScreening.html
Added cervical cancer screening and assessment forms for BA input
> Added cervical cancer screening and assessment forms

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLLostToFollowupReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLLtfuReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/defaulterTracing/BookingDateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/defaulterTracing/LastDefaulterTracingDateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/defaulterTracing/BookingDateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/defaulterTracing/LastDefaulterTracingDateDataEvaluator.java
- omod/src/main/webapp/resources/htmlforms/cervicalCancerScreening.html
Added Defaulter tracing booking date and tracing date in Lost to followup report.
> Added booking date and tracing date in Lost to followup report

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLLostToFollowupReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLLtfuReportBuilder.java
Updated Lost to follow up report to get Last appointment and visit dates from ETL tables
> Updated Lost to follow up report to get Last appointment and visit dates from ETL tables

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/resources/content/kenyaemr.common.xml
Aligned Cacx screening forms with JOOTRH metadata - UUIDs
> Aligned Cacx screening forms with JOOTRH metadata - UUIDs

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Updated MOH731 TB screening and Presumed TB to include active clients with 30 plus TCA
> Updated MOH731 TB screening and Presumed TB to include active clients with 30 plus TCA

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ETLLTFUWithDateRangeCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ETLLostToFollowupCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Updated lost to followup reports to have documented ltfu only include for those who discontinuation_reason is lost to follow
up
> Updated lost to followup reports to have documented ltfu only include for those who  discontinuation_reason is lost to follow up

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimCohortLibrary.java
Updated Datim TX_RTT to use the current Lost To Follow up query with return to care on the datim periodd
> Updated Datim TX_RTT to use the current Lost To Follow up query with return to care on the datim period

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLLtfuReportBuilder.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/mchms/MchmsCarePanelFragmentController.java
Bug fix on MCH overview used correct Mchms encounter concept and updated overview hts test logic
> Bug fix on MCH overview used correct Mchms encounter concept and updated overview hts test logic

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsLinkage.html
- omod/src/main/webapp/resources/htmlforms/mchms/mchmsEnrollment.html
Added other cadre text field in hts linkage, showed other facility on edit in hts initial and retest
> Added other cadre text field in hts linkage, showed other facility on edit in hts initial and retest

- omod/src/main/webapp/resources/htmlforms/hiv/hivDiscontinuation.html
- omod/src/main/webapp/resources/htmlforms/hts/htsLinkage.html
Added adherence counsellor  in cadre types hts linkage and non communicable diseases in cause of death hiv dis
continuation
> Added adherence counsellor  in cadre types hts linkage and non communicable diseases in cause of death hiv dis continuation

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/EligibleForFastrackPatientsCalculation.java
- omod/src/main/webapp/resources/htmlforms/mchms/mchmsAntenatalVisit.html
Bug fix on ART Fast track - used TCA concept alongside greencard encounter made ANC visit number mandatory"
> Bug fix on ART Fast track - used TCA concept alongside greencard encounter made ANC visit number mandatory

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/hivTesting/HtsHistoryFragmentController.java
Aligned strategy and entry points to hts labels, updated community tested and facility tested indicators in M
OH731
> Aligned strategy and entry points to hts labels, updated community tested and facility tested indicators in M OH731

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- omod/src/main/webapp/resources/scripts/KenyaAddressHierarchy.js
Updated MOH731 Tested Facility vs Tested community to include new settings  field, Added Embakasi West sub county and related wards
> Updated MOH731 Tested Facility vs Tested community to include new settings  field, Added Embakasi West sub county and related wards

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Handled variations in hts strategy naming to include where HTS done MOH731
> Handled variations in hts strategy naming to include where HTS done MOH731

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Bug fix on MOH731 deliveryFromHIVPositiveMothers to pick only mothers within the start and end date and not all
> Bug fix on MOH731 deliveryFromHIVPositiveMothers to pick only mothers within the start and end date and not all

- api/src/main/distro/metadata/identifierTypes.xml
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/wrapper/PatientWrapper.java
- api/src/main/resources/content/kenyaemr.common.xml
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
Add client number for use in programs like HTS
> add client number identifier

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/hts/PatientsEligibleForHtsRetestCalculation.java
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
hts updates: made retest available with initial form,validated disability, no results for inconclusive tests
> hts updates: made retest available with initial form,validated disability, no results for inconclusive tests

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsLinkage.html
Updated linkage,initial and retest forms for referral_to concept and logic
> Updated linkage,initial and retest forms for referral_to concept and logic

- omod/src/main/webapp/resources/htmlforms/hts/htsLinkage.html
Reverted referral facility in referral and linkage concept 162724
> Reverted referral facility in referral and linkage concept 162724

- omod/src/main/webapp/resources/htmlforms/hiv/moh257VisitSummary.html
Added validation for adverse drug reactions incase you choose no reactions
> Added validation for adverse drug reactions incase you choose no reactions

- omod/src/main/webapp/resources/htmlforms/hiv/hivDiscontinuation.html
Added red asterix for mandatory death reason in hiv discontinuation if reason is death
> Added red asterix for mandatory death reason in hiv discontinuation if reason is death

- omod/src/main/webapp/resources/htmlforms/hiv/hivDiscontinuation.html
Removed NCD such as Diabetes and hypertension as a death reason to specific death reason
> Removed NCD such as Diabetes and hypertension as a death reason to specific death reason

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/HTSStrategyConverter.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/hivTesting/HtsHistoryFragmentController.java
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Added SNS - Social Networks as a test strategy
> Added SNS - Social Networks as a test strategy

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/KPTypeConverter.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/PopulationTypeArtDataEvaluator.java
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Added prisoner and transgender in key popultaions in htsInitial, htsRetest, greencard and converters
> Added prisoner and transgender in key popultaions in htsInitial, htsRetest, greencard and converters

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/resources/content/kenyaemr.common.xml
- omod/src/main/webapp/resources/htmlforms/hts/hivSelfTesting.html
Stk form: Added HTS self test form for persons who are not enrolled,not tested positive and not linked
> Stk form: Added HTS self test form for persons who are not enrolled,not tested positive and not linked

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/DatimReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimCohortLibrary.java
Updated HTS_INDEX_DOCUMENTED_NEGATIVE, used non contacts dimension for dissagregation
> Updated HTS_INDEX_DOCUMENTED_NEGATIVE, used non contacts dimension for dissagregation

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/DatimReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimIndicatorLibrary.java
TB_PREV_ENROLLED_ART_INITIATED_TPT and TB_PREV_NEWLY_ENROLLED_ART_INITIATED_TPT
> TB_PREV_ENROLLED_ART_INITIATED_TPT and TB_PREV_NEWLY_ENROLLED_ART_INITIATED_TPT

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/HTSStrategyConverter.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/hivTesting/HtsHistoryFragmentController.java
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
…nitiated Testing(PITC) to HP: Hospital Patient Testing
> Updated HTS Startegy in initial,retest and converter of HP:Provider Initiated Testing(PITC) to HP: Hospital Patient Testing

- omod/src/main/webapp/resources/htmlforms/cervicalCancerScreening.html
Cervical cancer screening: Made screening type mandatory and validated for negative/normal results for no treatment
> Cervical cancer screening: Made screening type mandatory and validated for negative/normal results for no treatment

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Updated MOH731 Infant ARV prophylaxis given at ANC,LD and PNC less than 8 weeks
> Updated MOH731 Infant ARV prophylaxis given at ANC,LD and PNC less than 8 weeks

- omod/src/main/webapp/resources/htmlforms/mchcs/mchcsDiscontinuation.html
> KHP3-286 Add Transfer out as an option on the HEI discontinuation form

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/mchms/PatientsOnMCHReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/pmtct/PatientsOnMCHCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/pmtct/PatientsOnMCHCohortDefinition.java
- api/src/main/resources/content/kenyaemr.mchms.xml
> Currently in mch - updated requested changes

- api/src/main/distro/metadata/programs.xml
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/vmmc/EligibleForVmmcProgramCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/VMMCMetadata.java
- api/src/main/resources/content/kenyaemr.vmmc.xml
- api/src/main/resources/moduleApplicationContext.xml
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/vmmc/VmmcCarePanelFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/vmmc/VmmcEnrollmentSummaryFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/vmmc/VmmcOutcomeSummaryFragmentController.java
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcDiscontinuation.html
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcEnrollment.html
Initial vmmc program work - enrollment form, discontinuation,program and care panels
> Initial vmmc program work - enrollment form, discontinuation,program and care panels

- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcDiscontinuation.html
> KHP3-554 Avail Discontinuation Form for VMMC Module

- api/src/main/resources/content/kenyaemr.common.xml
> KHP3-462 Deactivating the CACX Screening form until when the client is eligible

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/PhysicalAddressCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/art/ViralLoadCategoriesCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLLostToFollowupReportBuilder.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/facilityDashboard/MiniFacilityDashboardFragmentController.java
- omod/src/main/webapp/fragments/facilityDashboard/miniFacilityDashboard.gsp
- omod/src/main/webapp/pages/facilityDashboard/miniFacilityDashboardHome.gsp
- omod/src/main/webapp/pages/home.gsp
Khp3 571-Lost To Follow Up Line list: Add column for physical address to help in tracing  
-Choose the nearest landmark which is the the nearest health center
> Khp3 571-Lost To Follow Up Line list: Add column for physical address to help in tracing   

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/VMMCMetadata.java
- api/src/main/resources/content/kenyaemr.vmmc.xml
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcCircumcisionProcedure.html
> KHP3-381 Avail Circumcision Procedure Form for VMMC Module

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/NeedsCACXTestCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/VMMCMetadata.java
- api/src/main/resources/content/kenyaemr.vmmc.xml
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcPostOperationAssessment.html
> KHP3-382 Avail Immediate Post Operation Discharge for VMMC Module

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Updated hts initial and confirmatory forms on results given for inconclusive/invalid results given requiremen
t
> Updated hts initial and confirmatory forms on results given for inconclusive/invalid results given requirement

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/vmmc/PatientsEligibleForVMMCProcedureCalculation.java
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Updated a NPE on patientsEligiblrForVmmcProcedure calc and added art start date for positives
> Updated a NPE on patientsEligibleForVmmcProcedure calc and added art start date for positives

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/vmmc/PatientsEligibleForVMMCPostOperationCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/util/VmmcConstants.java
- api/src/main/resources/content/kenyaemr.vmmc.xml
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcClientFollowup.html
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Added eligibility calculation for vmmc post operation and followup, added repeating section for adverse event
> Added eligibility calculation for vmmc post operation and followup, added repeating section for adverse events

- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcClientFollowup.html
Updated on edit for adverse events - vmmc followup
> Updated on edit for adverse events - vmmc followup

- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcEnrollment.html
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Vmmc mandatory fields in vmmcEnrollment form and vmmcMedicalHistoryandExamination form
> Vmmc mandatory fields in vmmcEnrollment form and vmmcMedicalHistoryandExamination form

- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Code clean up of hidden files - clearing of hidden fields if not asseted/consented
> Code clean up of hidden files - clearing of hidden fields if not asseted/consented

- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcClientFollowup.html
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcEnrollment.html
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Updated vmmc enrollment,medical history and followup UI according to BA feedback mostly validations and required fields
> Updated vmmc enrollment,medical history and followup UI according to BA feedback mostly validations and required fields

- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcClientFollowup.html
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Updated vmmcFollowup form removed repeating sections for adverse events, updated no pionter on in good health for urethral discharge
> Updated vmmcFollowup form removed repeating sections for adverse events, updated no pionter on in good health for urethral discharge

- api/src/main/java/org/openmrs/module/kenyaemr/HivConstants.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/MissedLastAppointmentCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/LostToFollowUpCalculation.java
Updated LTFU to 31+ days and use MOH257 and HIV greencard form together with HIV concultation to determine missed appointment and ltfu flags
> Updated LTFU to 31+ days and use MOH257 and HIV greencard form together with HIV concultation to determine missed appointment and ltfu flags

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Added referral services for HTS initial and Retest tested Negative and Validated for gender on vmm
c
> Added referral services for HTS initial and Retest tested Negative and Validated for gender on vmmc

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/vmmc/EligibleForVmmcProgramCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/VMMCMetadata.java
Updated VMMC eligibility and removed age limit, updated vmmc medical history and physical examination full name
> Updated VMMC eligibility and removed age limit, updated vmmc medical history and physical examination full name

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
Add Priority population on the following forms in HIV Green card. The field should have below options
1. Fisher folk
2. Truck driver
3. Adolescent and young girls
4. Prisoner
5. Military -
> KHP 3-855: Add Priority population on the following forms

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/vmmc/PatientsEligibleForVMMCFollowupFormCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/vmmc/PatientsEligibleForVMMCHistoryAndExaminationFormCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/vmmc/PatientsEligibleForVMMCProcedureCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/util/VmmcConstants.java
- api/src/main/resources/content/kenyaemr.vmmc.xml
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Updated availability for vmmc history and exam form to before one fills the circumcision procedure
> Updated availability for vmmc history and exam form to before one fills the circumcision procedure

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Added prepopulations for pop type and ever tested for hts initial from hts eligibility screenin
g
> Added prepopulations for pop type and ever tested for hts initial from hts eligibility screening

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/ActivePatientSnapshotReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/HeightAtArtDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/HeightAtArtDataEvaluator.java
> added height in Active on ART Line list

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/ActivePatientsPopulationTypeDataEvaluator.java
Add population type in ART register report
> Add population type in report

- api/pom.xml
- omod/pom.xml
- pom.xml
> Bumped version to v18.2.0

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/ActivePatientsPopulationTypeDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/SummariesFragmentController.java
Cherry Picked:
f55995897b2bc580e1f56b8bbedeefd988c41219 -- done
ae1439f87f06effe1930cf7201350989df5e1755 -- done
> Cherry pick april2022 v2

- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcEnrollment.html
- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Added control to specify other vmmc history referral, added client type in vmmc enrolment and validations
> Added control to specify other vmmc history referral, added client type in vmmc enrolment and validations

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/art/ViralLoadCategoriesCalculation.java
Vl category calculation flag bug fix
> Vl category bug fix

- api/src/main/distro/metadata/identifierTypes.xml
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/MissingAllRegistrationIdentifiersCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/wrapper/PatientWrapper.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/PatientSummaryFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/fragments/patient/patientSummary.gsp
Added a patient banner for patients missing all registration identifiers - Huduma no,patient clinic no,national ID, passport no and birth cert n
o
> Added a patient banner for patients missing all registration identifiers - Huduma no,patient clinic no,national ID, passport no and birth cert no

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/AllPatientsReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/NationalIdentifiersTypeConverter.java
- api/src/main/resources/content/kenyaemr.common.xml
> KHP3-906 - Person identifier line list

- api/src/main/resources/content/kenyaemr.common.xml
> KHP3-906 Person identifier line list, added missing identifiers linelist

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
Prepopulated weight and height if collected through traige on the same date for HIV greencard
> Prepopulated weight and height if collected through traige on the same date for HIV greencard

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
Disable currently on TPT if a client is enrolled in TB program - prepopulated from enrollment on TB progra
m
> Disable currently on TPT if a client is enrolled in TB program - prepopulated from enrollment on TB program

- omod/src/main/webapp/fragments/patient/editPatient.gsp
> hiding driving license for persons under 18 years during registration

- api/src/main/java/org/openmrs/module/kenyaemr/EmrActivator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/AllPatientsReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ScheduledAppointmentCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/NationalIdentifiersTypeConverter.java
- api/src/main/resources/content/kenyaemr.common.xml
- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/fragments/patient/patientSearchResults.gsp
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
- omod/src/main/webapp/resources/scripts/controllers/patient.js
93a6145aebeeebe91e9583795e03878be1fd98fb -- done
8b400f1622632c982f600c2d3eb23601867830b1 -- done
7a9b545a2edc07e8ae355a4212a2839a711a8ddc -- done
71bb060169a0181ce6ff2bfe5cbe5b1b6455d99e -- done
a7d5b839d2eebe8f43b9265cb55ebd0001529eec -- done
3e0a40bc2de7a6471fa7c1667cb198a7e52dc866 -- done
aa1f91e5ab6adc14fd664e187f7003196025f0c1 -- done
f44e90b48fa8b116dc9eb3c89a36d025481d3ece -- done
2b295323dc42ac60b1e6153ba6a4460295f6f75b -- done
0ce96190c2e1f9431e2de929e014092b4b916117 -- done
4667af6962763a2fa562b13492cc0331127addec -- done
93b1ec054e808a8cc90ebd06f26c99561ab0a3d9 -- done
ed66d4d76c53b3ab6f5ff2f2540c9f94993769a5 -- done
> Cherry pick28042022

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Updated negative referral obsgroup to 163180 - a convset which acts as a datatype discriminator
> Updated negative referral obsgroup to 163180 - a convset which acts as a datatype discriminator

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/AllCd4CountCalculation.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/SummariesFragmentController.java
- omod/src/main/webapp/fragments/summaries.gsp
> All cd4 count calculation

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
Added converters to handle marital status, occupation,gender,education,country,county and added mfl code
> Added converters to handle marital status, occupation,gender,education,country,county and added mfl code

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiDataExchangeFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiUtilsDataExchange.java
Added OAUTH2 token request for client registry
> Added OAUTH2 token request for client registry

- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/resources/scripts/KenyaAddressHierarchy.js
Updated KenyaAddressHierarchy, added messages for mandatory fields meant for UPI post
> Updated KenyaAddressHierarchy, added messages for mandatory fields meant for UPI post

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiUtilsDataExchange.java
Disabled UPI Client Registry SSL Validation
> Disabled UPI Client Registry SSL Validation

- omod/src/main/webapp/fragments/patient/editPatient.gsp
> Added missing variables warnings/lables for UPI post next to respective inputs

- omod/src/main/webapp/fragments/patient/editPatient.gsp
Updated create patient button to be active after the post to CR button is clicked
> Updated create patient button to be active after the post to CR button is clicked

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiDataExchangeFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiUtilsDataExchange.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
set network timeouts and alerts for network errors
> set network timeouts and alerts for network errors

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
> Create a list of countries

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/MissingNUPIIdentifierCalculation.java
- api/src/main/resources/content/kenyaemr.common.xml
> updated patients missing national unique patient identifier calculation

- omod/src/main/webapp/fragments/patient/editPatient.gsp
Added spinners to show activity during waiting while pulling/posting upi data
> Added spinners to show activity during waiting while pulling/posting

- omod/src/main/webapp/fragments/patient/editPatient.gsp
Add spinners to upi pull mod one
> Add spinners to upi pull mod one

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/publicHealthActionReport/PublicHealthActionCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/publicHealthActionReport/PublicHealthActionIndicatorLibrary.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiDataExchangeFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/resources/scripts/upiVerificationUtils.js
1. Fixed spinner on post. 
2. Fix post action and error handling. 
3. Enhanced handling of countrycodes,occupation,marital status,counties and education 
4. Fixed token fetch on validate identifier async 
5. Form field validation and error display 6. Code cleanup
> Upi Form Enhancement

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
Fixed the issue of client registry globals being overwritten by defaults
> Fixed the issue of client registry globals being overwritten by defaults

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiDataExchangeFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
1. Fix upi post data
2. Restrict data edit until remote PUT is enabled
> Multiple Fixes

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
Added ccc number in UPI post payload
> Added ccc number in UPI post payload

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiDataExchangeFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiUtilsDataExchange.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
> Removed some debug messages

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
Reverts palladiumkenya/openmrs-module-kenyaemr#1149
> Revert "Cherry-pick on KenyaEmr"

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/PublicHealthActionReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/publicHealthActionReport/PublicHealthActionCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/publicHealthActionReport/PublicHealthActionIndicatorLibrary.java
Reverts palladiumkenya/openmrs-module-kenyaemr#1162
> Revert "Added HEI of HIV+ parent with undocumented HIV status indicator to Cl…"

- omod/src/main/webapp/fragments/patient/editPatient.gsp
Bug fix on patient gender on editPatient - patient UPI posting picking default female
> Bug fix on patient gender on editPatient - patient UPI posting picking default female

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/iitRiskScore/IitPatientRiskScoreFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/clinician/ClinicianViewPatientPageController.java
- omod/src/main/webapp/fragments/iitRiskScore/iitPatientRiskScore.gsp
- omod/src/main/webapp/pages/clinician/clinicianViewPatient.gsp
- pom.xml
Added IIT risk score fragment on patient profile if risk score exists and pulling from ML mode
l
> Added IIT risk score fragment on patient profile if risk score exists and pulling from ML model

- .github/workflows/cicd_process.yml
> update tomcat commands

- omod/src/main/webapp/resources/htmlforms/cervicalCancerScreening.html
> KPH3-1635 - Updated cacx edit form on preview

- omod/src/main/webapp/resources/htmlforms/vmmc/vmmcMedicalHistoryExamination.html
Updated VMMC History and examination form - relaxed procedure for unknown hiv status
> Updated VMMC History and examination form - relaxed procedure for unknown hiv status

- omod/src/main/webapp/resources/scripts/KenyaAddressHierarchy.js
> Separated joined Gem wards - West gemnorth gem

- api/src/main/java/org/openmrs/module/kenyaemr/util/EmrUtils.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/ReportPageController.java
- omod/src/main/webapp/fragments/report/reportRequestForm.gsp
> Cleaned up sub county based filtering for MOH731B plus report from implementing subcounties entries done

- omod/src/main/webapp/resources/scripts/KenyaAddressHierarchy.js
Updated mispelt Bomachoge chache as Bamachoge chage as MOH address dictionary
> Updated mispelt Bomachoge chache as Bamachoge chage as MOH address dictionary

- api/pom.xml
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/ActivePatientSnapshotReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/ActiveInProgramConverter.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/ActiveInMchDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/ActiveInOtzDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/ActiveInOvcDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/ActiveInTbDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ActiveInMchDataDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ActiveInOtzDataDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ActiveInOvcDataDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ActiveInTbDataDefinitionEvaluator.java
- distro/pom.xml
- install/pom.xml
- omod/pom.xml
- pom.xml
Added endDate based evaluators for in PMTCT,OVC,OTZ and TB and a converter in Active Patients linelist,
Bumping to v18.3.2
> Added endDate based evaluators for in PMTCT,OVC,OTZ and TB and a converter in Active Patients linelist, Bumping to v18.3.2

- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/ReportPageController.java
- omod/src/main/webapp/fragments/report/reportRequestForm.gsp
Updated reportRequest form failing on vl, monthly and quarterly reports generation
> Updated reportRequest form failing on vl, monthly and quarterly reports generation

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
Add the final criteria for stability assessment which is missing in KenyaEmr Green card
> Add the final criteria for stability assessment

- omod/src/main/webapp/resources/scripts/KenyaAddressHierarchy.js
Updating of the KenyaEmr address hierarchy
> Updating of the KenyaEmr address hierarchy

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/ovc/PatientsOnOVCReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ovc/PatientsOnOVCCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/util/EmrUtils.java
- omod/src/main/webapp/fragments/report/reportRequestForm.gsp
Revised currently on OVC clients to tx_curr and currently on ovc. Added end date parameter to the report
> Reports bugs fixes. 

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
Added gender and dob as required fields when registering kdod
> added gender and dob as required fields when registering kdod

- api/src/main/java/org/openmrs/module/kenyaemr/api/NUPIcccService.java
- api/src/main/java/org/openmrs/module/kenyaemr/api/db/NUPIcccDAO.java
- api/src/main/java/org/openmrs/module/kenyaemr/api/db/hibernate/HibernateNUPIcccDAO.java
- api/src/main/java/org/openmrs/module/kenyaemr/api/impl/NUPIcccServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/nupi/NUPIcccSyncRegister.java
- api/src/main/java/org/openmrs/module/kenyaemr/nupi/UpiUtilsDataExchange.java
- api/src/main/java/org/openmrs/module/kenyaemr/task/UpdateCCCnumbersTask.java
- api/src/main/resources/NUPIcccSyncRegister.hbm.xml
- api/src/main/resources/moduleApplicationContext.xml
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiDataExchangeFragmentController.java
- omod/src/main/resources/config.xml
- omod/src/main/resources/liquibase.xml
- omod/src/main/webapp/fragments/patient/editPatient.gsp
1) Missing ccc number
1. check for patients with upi and with ccc (paginate)
2. for each of the patients above we check on register ccc is synced
3. if on API they dont have ccc, we add the ccc
2) ART and ccc (Make ccc mandatory if on ART)
1. If patient has ccc, send ccc (isOnART = true) if not, send (isOnART = false)
2. If patient is not on ART, ccc is optional. Later on scheduled task, add the ccc
also when enrolling patient on ART, enforce ccc number exists or is added at this point
3) Add country and isOnART to POST params
- add country code in caps to POST params
4) Add country code to URL 
- Make sure country code (e.g KE) is added to URL e.g https://dhpstagingapi.health.go.ke/partners/registry/search/KE/
5) Add country select box in the verification page
- Add the select
> Nupi ccc sync

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/sgbv/SGBVRegisterReportBuilder.java
- api/src/main/resources/content/kenyaemr.common.xml
- omod/src/main/webapp/resources/htmlforms/hiv/hivDiscontinuation.html
Added red asterix for required specific cause of death, renamed sgbv register in common reports to align
> Added red asterix for required specific cause of death, renamed sgbv register in common reports to align

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/nupi/MissingNUPIIdentifierReportBuilder.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
1. Fixed illegal character on counties on registration page 
2. Fixed Non Critical 'Missing NUPI report' format exception on error column
> Fixed illegal character on counties on registration page

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/GreenCardVelocityCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimCohortLibrary.java
Removed commit on removing clients stopped drugs from TxCurr throwing mysql errror max_allowed_packet
> Removed commit on removing clients stopped drugs from TxCurr throwing mysql errror max_allowed_packet

- api/src/main/java/org/openmrs/module/kenyaemr/nupi/UpiUtilsDataExchange.java
- api/src/main/java/org/openmrs/module/kenyaemr/task/GetNUPIforAllTask.java
> Better NUPI Error management

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
Updated MOH 731 testedForHivInMchmsTotal to include testedHivPositiveInPNCWithin6weeks
> Updated MOH 731 testedForHivInMchmsTotal to include testedHivPositiveInPNCWithin6weeks

- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/upi/UpiVerificationHomePageController.java
- omod/src/main/webapp/pages/upi/upiVerificationHome.gsp
> Updated UPI client verification summary to include current in HIV

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
Validated Refill date on hivGreencard form against tca : Refill should never be greater than tca
> Validated Refill date on hivGreencard form against tca : Refill should never be greater than tca

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
> Added a question in hivGreencard form to ask for consent on reminders

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/heiCohortAnalysis/HcaCohortLibrary.java
Updated hei cohort analysis to include all Hei that were tested for PCR at 12 months
> Updated hei cohort analysis to include all Hei that were tested for PCR at 12 months

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
Wondering whether we need to discontinue those on IPT automatically
> Ensure persons enrolled in TB program do not fill IPT questions

- api/pom.xml
- distro/pom.xml
- install/pom.xml
- omod/pom.xml
- omod/src/main/resources/liquibase.xml
- pom.xml
Disabled the Get all Patients NUPI scheduler
> Disabled the Get all Patients NUPI scheduler

- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/upi/UpiVerificationHomePageController.java
Speed Enhancement on NUPI Verification Page
> Speed Enhancement on NUPI Verification Page

- api/src/main/java/org/openmrs/module/kenyaemr/nupi/UpiUtilsDataExchange.java
- api/src/main/java/org/openmrs/module/kenyaemr/task/GetNUPIforAllTask.java
- omod/src/main/resources/liquibase.xml
Restored the GET NUPI FOR ALL task with a check on PENDING status
> Restored the GET NUPI FOR ALL task with a check on PENDING status

- api/pom.xml
- omod/pom.xml
- omod/src/main/resources/liquibase.xml
- pom.xml
> Removed Scheduler

- omod/src/main/webapp/resources/htmlforms/mchcs/mchcsDiscontinuation.html
In the said form, add the following in the reasons for discontinuation section.
- Lost to follow up 
- Discharged at 18 months
> Child Welfare Services Discontinuation Form Enhancements

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsAntenatalVisit.html
add a field which allows the user to indicate YES if Deworming medication has been given and NO if not given.
> Add Deworming section in MCH Antenatal visit form

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsAntenatalVisit.html
Add blood sugar testing for diabetes in MCH Antenatal visit form
>  Add blood sugar testing for diabetes in MCH Antenatal visit form

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsDelivery.html
> KHP3-935 Delivery Form Enhancements

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsDischarge.html
> KHP3-949 Discharge and Referral Form Enhancement

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/PatientUtilsFragmentController.java
- omod/src/main/webapp/resources/htmlforms/mchcs/mchcsFollowupVisit.html
> KHP3-950 CWC Follow Up Form Enhancements

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsPostnatalVisit.html
> KHP3-963 MCH Postnatal Visit Form Enhancements

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/EmrUtilsFragmentController.java
- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
> Added recency ID in hiv enrollment, validation for unique number and prepopulation from hts retest

- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Added rececny testing in HTS initial form and prepopulate the check question if recency had been added in preceeding forms
> Added rececny testing in HTS initial form and prepopulate the check question if recency had been added in preceeding forms

- omod/src/main/webapp/fragments/patient/editPatient.gsp
> Changed prisoner-id to prison-id

- api/src/main/distro/metadata/identifierTypes.xml
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/wrapper/PatientWrapper.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/fragments/patient/editPatient.gsp
> Prisoner verification updates: Added prisoner-ID for verification, Added prisoner-ID for posting and using variables from CR

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/ActivePatientSnapshotReportBuilder.java
Removed Date Conversion from a non-date column (Case Manager)
> KHP3-2776: Error generating active on ART linelist

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/EligibleForPregnancyTestCalculation.java
- omod/src/main/webapp/resources/htmlforms/mchms/mchmsAntenatalVisit.html
- omod/src/main/webapp/resources/htmlforms/triage.html
Triage form enhancement
- Inclusion of HPV Vaccination status for females aged 9 to 14 years. Add a variable in the triage form to record if the client has received HPV vaccination.
-Also add Pregnancy screening variables in the triage form for the females of reproductive age. Allow the user to see the pregnancy screening variables for clients aged 10 years and above.
- Eligible for pregnancy test flag calculation
MCH Antenatal Visit Form Enhancement
Include the following variables in the MCH Antenatal visit form in KenyaEMR which are currently missing.
-Treatment section
- Deworming 
- Blood sugar testing for diabetes
- Hepatitis B virus screening and treatment
- Female Genital mutilation complication
- Post-partum family planning
- Minimum Package of Care
> Anc and triage form enhancement

- omod/src/main/webapp/resources/htmlforms/mchcs/mchcsFollowupVisit.html
> KHP3-2647 Change the styling in referral section in cwc followup form

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsAntenatalVisit.html
Updating duplicated conceptId = 165302 added as uuid and removed commented code
> Updating duplicated conceptId = 165302 added as uuid and removed commented code

- api/src/main/java/org/openmrs/module/kenyaemr/form/velocity/EmrVelocityFunctions.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Added a config for Recency Testing sites called is IS_Recency_SITE. If its true, hts_initial, retest and hiv_enrollment will avail recency_Id
> Added a config for Recency Testing sites called is IS_Recency_SITE. If its true, hts_initial, retest and hiv_enrollment will avail recency_Id

- omod/src/main/webapp/resources/htmlforms/triage.html
Client Vaccinated against HPV for girls between the age of 9 to 14 years.
Pregnancy test for female starting the age of 10 years
> Client Vaccinated against HPV  change

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/HighRiskClientCatogorizationCalculation.java
Evaluates the calculation,
PMTCT client enrolled in mch program
Allow new HV positive irrespective of time identified ,
All infected AGYW < 19 including OVC & DREAM girls,
All clients with detectable VL > 200 copies/ml at baseline for known positive or anytime in the PMTCT followUP period,
Tranfer Ins or Transist clients.
> Highrisk client categorization

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsAntenatalVisit.html
- omod/src/main/webapp/resources/htmlforms/mchms/mchmsPostnatalVisit.html
> Dual test kit not showing Syphilis results in anc and pcn MCH forms for negatives

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/HighRiskClientCategorizationCalculation.java
Categorizing only positive and enrolled clients as high risk under pmtct age 10-18,vl>200 and OVC
> Categorizing only positive and enrolled clients as high risk under pmtct age 10-18,vl>200 and OVC

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsDelivery.html
> Updated ART prophylaxis for mother - added started at maternity cleaned up duplications on baby prophylaxis

- omod/pom.xml
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
- pom.xml
> New PMML HTS ML Model

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/wrapper/PatientWrapper.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/upi/UpiDataExchangeFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/upi/UpiVerificationHomePageController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/pages/upi/upiVerificationHome.gsp
Added updating functionality for NUPI CRS-IPRS verification errors - a verified with errors page and updating mechanism
> Added updating functionality for NUPI CRS-IPRS verification errors - a verified with errors page and updating mechanism

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/ActivePatientsSnapshotCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/util/EmrUtils.java
> KHP3-3020: Update Active on ART Patients Linelist report to work on multitenancy setup

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsDelivery.html
Description
Validate the section capturing the referrals i.e. hide reason for referral if the user selects N/A for referred to question.
> Validate the section capturingthe referralsaccordingly

- api/src/main/java/org/openmrs/module/kenyaemr/nupi/UpiUtilsDataExchange.java
> Removed some logging messages

- omod/src/main/webapp/resources/htmlforms/mchcs/mchcsDiscontinuation.html
> Added death reasons - mortality specifications for HEI discontinuation

- omod/src/main/webapp/fragments/providerAction/providerActions.gsp
- omod/src/main/webapp/fragments/visitMenu.gsp
Added O3 link to patient page - Provider Actions Menu
> Added O3 link to patient page - Provider Actions Menu

- omod/src/main/webapp/resources/htmlforms/mchcs/mchcsFollowupVisit.html
Fixed validation error for under 1 on LL Nets and duplicated deworming refill date and dosage units
> Fixed validation error for under 1 on LL Nets and duplicated deworming refill date and dosage units

- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
Updated transfer in date to allow dates after encounter/enrollment date and not future dates
> Updated transfer in date to allow dates after encounter/enrollment date and not future dates

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
- omod/src/main/webapp/resources/htmlforms/sari/sariExit.html
- omod/src/main/webapp/resources/htmlforms/sari/sariFollowup.html
- omod/src/main/webapp/resources/htmlforms/sariIliScreening.html
- omod/src/main/webapp/resources/htmlforms/sariScreening.html
- omod/src/main/webapp/resources/htmlforms/triage.html
Remove non functional Dont know from greencard and triage form
> Remove non functional Dont know from greencard and triage form

- api/src/main/java/org/openmrs/module/kenyaemr/chore/UpdateDoseConceptToAllowDecimals.java
> Added a chore that updates dose concept 1443 to allow decimals

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
> Updated WHO staging to include OIs corresponding to each stage

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/PatientsWithAdvancedHivDiseaseCalculation.java
> Added a flag for patients with Advanced HIV disease

- api/src/main/java/org/openmrs/module/kenyaemr/form/velocity/EmrVelocityFunctions.java
Updated fetching MFL from Kenyaemrservice method rather than globalProperty as some sites do not have defaultMFL Global property
> Updated fetching MFL from Kenyaemrservice method rather than globalProperty as some sites do not have defaultMFL Global property

- omod/src/main/webapp/resources/htmlforms/mchcs/mchcsEnrollment.html
> In the MCH Child enrollment form, add 2 types of delivery missing

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLLtfuReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/ipt/PhysicalAddressDataEvaluator.java
Add a column of Physical address in LTFU and modification of Physical address query
> Add column of Physical address in LTFU

- api/src/main/java/org/openmrs/module/kenyaemr/form/action/HivGreenCardPostSubmissionAction.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/EmrUtilsFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/clinician/ClinicianViewPatientPageController.java
- omod/src/main/webapp/pages/clinician/clinicianViewPatient.gsp
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
- pom.xml
iit risk score updates on patient profile and greencard
> iit risk score updates on patient profile and greencard

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/GreenCardVelocityCalculation.java
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
> Allow display of chronic illnesses if ever added to persist in subsequent GC encounters and remove mandatory if they exist

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/mchcs/MchcsCarePanelFragmentController.java
- omod/src/main/webapp/fragments/program/mchcs/mchcsCarePanel.gsp
Summary page for MCH Baby doesnt reflect the updated info i.e HEI had PCR results but the summary page indicates no test done.
Avail the following on the summary page
PCR results and date taken - Show all the PCRs results available and date done.
> Date , Test and order reason added in Summary page

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pama/PamaCareGiverLastVLDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pama/PamaCareGiverLastVLDateDataEvaluator.java
>  Pama report care giver: Added a condition for lab_test=(856,1305) for both latest VL results and results date

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/program/mchcs/MchcsCarePanelFragmentController.java
- omod/src/main/webapp/fragments/program/mchcs/mchcsCarePanel.gsp
Modification of the Summary page, additional of  antibody test if done to show in the HEI summary
> Add antibody test if done to show in the HEI summary

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pama/PamaCareGiverLastVLDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pama/PamaCareGiverLastVLDateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pama/PamaCareGiverLastVisitDateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pama/PamaCareGiverNextAppointmentDateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pama/PamaCareGiverStabilityStatusDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pama/PamaCareGiverSuppressionStatusDataEvaluator.java
> Updated missing data due to ungrouped results - pama care giver queries

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/CaseManagementFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditCaseManagerFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditRelationshipFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/PatientRelationshipsFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/admin/ProviderCaseManagerPageController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/registration/EditCaseManagerPageController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/registration/EditRelationshipPageController.java
- omod/src/main/webapp/fragments/patient/caseManagement.gsp
- omod/src/main/webapp/fragments/patient/editCaseManager.gsp
- omod/src/main/webapp/fragments/patient/patientRelationships.gsp
- omod/src/main/webapp/pages/admin/providerCaseManager.gsp
- omod/src/main/webapp/pages/clinician/clinicianViewPatient.gsp
- omod/src/main/webapp/pages/registration/editCaseManager.gsp
- omod/src/main/webapp/pages/registration/editRelationship.gsp
> Applying: Added a page for patients under a case manager - provider with names and start date

- omod/src/main/webapp/resources/htmlforms/triage.html
> Adding z-score field for children under 5 years for nutritional support

- omod/src/main/webapp/resources/htmlforms/triage.html
> Added implicitly z-score value - Numeric value from the outcomes

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/ZScoreUtilsFragmentController.java
- omod/src/main/webapp/resources/htmlforms/triage.html
> Wired z-score computation in triage form

- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
Related to this : https://github.com/palladiumkenya/openmrs-module-kenyaemr/pull/1536
> KHP3-3455: Create Rest Endpoint for Hiv Care Panel

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/ActivePatientSnapshotReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/BaselineCD4CountDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/BaselineCD4DateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/BaselineCD4DoneDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/BaselineCD4CountDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/BaselineCD4DateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/BaselineCD4DoneDataEvaluator.java
> Added CD4 baseline count and date columns in Active on ART linelist

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/MOH731Greencard/ETLMoh731GreenCardCohortLibrary.java
> Moh731 ctx dap

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsEnrollment.html
Handling tickets:
1. https://thepalladiumgroup.atlassian.net/browse/KHP3-3529
2. https://thepalladiumgroup.atlassian.net/browse/KHP3-3519
> Khp3 3529 hiv status before 1st anc

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/SearchFragmentController.java
- omod/src/main/webapp/resources/htmlforms/hiv/hivDiscontinuation.html
Provides a facility search in the transfer out form to allow users to provide transfer to facility mfl code.
> KHP3-3799: Enrich transfer out form to support art directory integration

- omod/src/main/webapp/resources/htmlforms/hiv/hivDiscontinuation.html
- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
> KHP3-3813: Support collection of mflCode of patient's transferred from facility

- api/src/main/java/org/openmrs/module/kenyaemr/form/action/HivGreenCardPostSubmissionAction.java
> Add auth to ML call

- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Removed HTS ML from initial and retest form
> Removed HTS ML from initial and retest form

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
Removed HTS ML from confirmatory form
> Removed HTS ML from confirmatory form

- omod/src/main/webapp/resources/htmlforms/hiv/hivEnrollment.html
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
> Rec id validation - to be 5 digits

- omod/src/main/webapp/resources/htmlforms/hts/htsLinkage.html
Put validation checks on ART linkage date vis-a-vis initiation date. Currently EMR accepts an earlier date prior to date initiated to be updated.
> Validate ART linkage date vis-a-vis initiation date

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/Moh745ReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/MOH745/Moh745CohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/MOH745/Moh745IndicatorLibrary.java
The work remaining on alignment is on the commented out treatment sections, which will be dealt with in another separate PR
> Align MOH 745 to new cervical cancer ETL

- api/src/main/resources/content/kenyaemr.common.xml
- api/src/main/resources/content/kenyaemr.hiv.xml
> Removing ReportConfiguration for covid reports in KenyaEMR causing inconsistencies

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/ETLTransferOutPatientsReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/hiv/FacilityTransferToCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/FacilityTransferToDataDefinition.java
Add a column for 'Facility transferred to' on the clients transferred out line list
> Add a column for 'Facility transferred to' on the clients transferred

- omod/src/main/webapp/resources/htmlforms/hiv/treatmentPreparation.html
ART Readiness assessment form missing medical criteria.
> ART Readiness assessment form missing medical criteria.

- api/src/main/resources/metadata/mfl_2014-05-12.csv
Added new facility named Kineni Health centre in Kisii
> Added new facility named Kineni Health centre in Kisii

- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/PatientUtilsFragmentController.java
- omod/src/main/webapp/resources/htmlforms/mchcs/mchcsFollowupVisit.html
> Cwc labs: Added labs information widget for cwc form with all the 6 tests from pcr 6 weeks to confirmatory 18 months

- omod/src/main/webapp/resources/htmlforms/mchms/mchmsDelivery.html
Blood loss during delivery can go up to 500mls for SVD and 1000mls for a cesarean birth.
> Blood loss during delivery limited to 20L

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/PamaReportCohortDefinitionEvaluator.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditRelationshipFragmentController.java
KHP3-3932: Dropping validation for pama care adding all TxCurr under 10 years with or without care giver
> KHP3-3932: Dropping validation for pama care adding all TxCurr under 10 years with or without care giver

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
- omod/src/main/webapp/resources/htmlforms/mchms/mchmsAntenatalVisit.html
- omod/src/main/webapp/resources/htmlforms/mchms/mchmsDelivery.html
- omod/src/main/webapp/resources/htmlforms/mchms/mchmsPostnatalVisit.html
In the HIV testing section, allow user to only see Determine and Dual test kits for HIV test 1. The forms affected are HTS Initial form, HTS Retest form, ANC Visit form, Delivery form and Postnatal form.
> In the HIV testing section, allow user to only see Determine

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
> Added zscore for children under 5 years - nutritional status

- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
> Validated male family planning statuses

- api/src/main/java/org/openmrs/module/kenyaemr/EmrConstants.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/SecurityMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/wrapper/PatientWrapper.java
- api/src/main/resources/moduleApplicationContext.xml
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/RegistrationUtilFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/nupi/NupiDataExchangeFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/nupi/NupiDuplicatesPageController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/page/controller/nupi/NupiVerificationHomePageController.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/fragments/nupi/nupiDataExchange.gsp
- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/pages/nupi/nupiDuplicates.gsp
- omod/src/main/webapp/pages/nupi/nupiVerificationHome.gsp
KHP3-4411 - Added the NUPI duplicates page which pulls data from NDWH
> Added the NUPI duplicates page which pulls data from NDWH

- api/src/main/java/org/openmrs/module/kenyaemr/wrapper/PatientWrapper.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/EmrUtilsFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/webapp/fragments/patient/editPatient.gsp
- omod/src/main/webapp/resources/htmlforms/hiv/hivGreenCard.html
> Added insurance cover - NHIF or other insurance in greencard and Registration form and validation on existing identifier

- omod/src/main/webapp/pages/nupi/nupiDuplicates.gsp
- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
KHP3-4385 add ml banner to hts initial and retest form
> KHP3-4385 add ml banner to hts initial and retest form

- omod/src/main/webapp/resources/htmlforms/hts/htsConfirmatoryTest.html
- omod/src/main/webapp/resources/htmlforms/hts/htsInitialTest.html
Added check for highest ML Risk
> Added check for highest ML Risk

- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
This PR removes unused imports, some changes are because of code-formating on vscode. In addition i have added required properties to `enrollmentHistory` to enable the feature work well.
> (feat) Add required properties to historicalEnrollment

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
Add metadata for inpatient visit
> add inpatient visit type

- api/src/main/java/org/openmrs/module/kenyaemr/advice/OutpatientToInpatientCheckinOnAdmissionRequest.java
Fix NPE when processing encounter aop
> check if visit is not null before checking out/in

- api/pom.xml
- distro/pom.xml
- install/pom.xml
- omod/pom.xml
- pom.xml
> Bumped to 18.7.2

- api/src/main/resources/metadata/mfl_2014-05-12.csv
> Added 5 more facilities

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/mat/EligibleForMATProgramCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/MATMetadata.java
- api/src/main/resources/content/kenyaemr.mat.xml
- omod/src/main/webapp/resources/htmlforms/mat/formDoesNotExistOn2x.html
Adding form metadata for MAT program
> add form metadata for MAT

- api/src/main/resources/moduleApplicationContext.xml
> wire mat metadata

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForChikungunyaCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForCholeraCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForDysenteryCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForHaemorrhagicCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForIliScreeningCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForMalariaCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForMeaslesCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForPoliomyelitisCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForRiftValleyFeverCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForSariScreeningCalculation.java
> Optimised the 8 DMI flags to calculate for only checked in clients :Clients with active visits

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForHaemorrhagicCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForRiftValleyFeverCalculation.java
nes for VHF , and used jaundice in general exam for RVF
> Updated Rift Valley Fever and Viral Haemoragic Fever - removed timelines for VHF , and used jaundice in general exam for RVF

- api/src/main/java/org/openmrs/module/kenyaemr/api/KenyaEmrService.java
- api/src/main/java/org/openmrs/module/kenyaemr/api/impl/KenyaEmrServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/model/AdditionalSearchParam.java
- api/src/main/java/org/openmrs/module/kenyaemr/util/RowMapper.java
- api/src/main/java/org/openmrs/module/kenyaemr/util/SqlQueryHelper.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
- pom.xml
Adds an endpoint for running queries. Adapted this from Bahmni
> (feat) add sql query endpoint

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/MOH705BReportBuilder.java
- api/src/main/resources/content/kenyaemr.common.xml
> include 705b bean and set report dimension

- .github/workflows/cicd_process.yml
github workflow to deploy to dev
> (OPS): Github workflow to allow auto-deployment to dev

- omod/src/main/webapp/resources/htmlforms/clinicalEncounter.html
> add realtime flagging of syndemic illnesses

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForDysenteryCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForHaemorrhagicCalculation.java
Updated mismatched blood in stool and unexplained bleeding concepts in dysentery and Viral haemorrhagic fever DMI calculations
> Updated mismatched blood in stool and unexplained bleeding concepts in dysentery and Viral haemorrhagic fever DMI calculations

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/resources/moduleApplicationContext.xml
- omod/src/main/java/org/openmrs/module/kenyaemr/EmrExternalUrlInterceptor.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/EditPatientFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/CorsInterceptor.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/EnableCors.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
- omod/src/main/resources/webModuleApplicationContext.xml
- omod/src/main/webapp/fragments/patient/editPatient.gsp
KHP3-5332  - NUPI Endpoint - 2.x
> KHP3-5332-NUPI-Endpoint-2.X

- api/src/main/distro/metadata/identifierTypes.xml
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
This PR adds SHIN to metadata deploy to support SHA features
> (feat) Add Social Health Insurance Number to meta data deploy

- omod/src/main/java/org/openmrs/module/kenyaemr/EmrOpenmrsUrlOverrideController.java
- pom.xml
Fix Appointments Version and Revert O3 redirects
> Fix appointments version revert o3 redirects

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/finacials/FacilityRevenueSummaries.java
> Updated monthly revenue summaries to include totals per reporting period

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForChikungunyaCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForCholeraCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForDysenteryCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForHaemorrhagicCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForMalariaCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForMeaslesCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForPoliomyelitisCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForRiftValleyFeverCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForSariScreeningCalculation.java
DMI flagging: Included Triage form for DMI flag calculations. Triage form has been enhanced to capture complaints
> DMI flagging: Included Triage form for DMI flag calculations. Triage form has been enhanced to capture complaints

- api/src/main/distro/metadata/concepts.xml
- api/src/main/distro/metadata/programs.xml
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/gbv/EligibleForGBVProgramCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/NeedsNewVLOrderCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/GBVMetadata.java
- api/src/main/resources/MigrateAppointmentsFromObs.sql
- api/src/main/resources/content/kenyaemr.gbv.xml
- api/src/main/resources/moduleApplicationContext.xml
- omod/src/main/resources/liquibase.xml
- omod/src/main/webapp/resources/htmlforms/gbv/formDoesNotExistOn2x.html
> Gbv program metadata

- omod/src/main/java/org/openmrs/module/kenyaemr/EmrExternalUrlInterceptor.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/CorsInterceptor.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
Added REST call to get latest Obs for patient
> Added REST call to get latest Obs for patient

- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
Added REST call to get latest Obs for patient for 3.x
> Added REST call to get latest Obs for patient for 3.x

- api/pom.xml
- distro/pom.xml
- install/pom.xml
- omod/pom.xml
- pom.xml
> Bumped version to 18.8.0

- api/src/main/distro/metadata/concepts.xml
- api/src/main/distro/metadata/programs.xml
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/GBVMetadata.java
- api/src/main/resources/content/kenyaemr.gbv.xml
Aligned GBV concepts to CHEB Obunge ETLed concepts - program, encounter and forms
> Aligned GBV concepts to CHEB Obunge ETLed concepts - program, encounter and forms

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/CCCDefaulterTracingRegisterReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/defaulterTracing/DateOfFinalOutcomeDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/defaulterTracing/DateOfFinalOutcomeDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/defaulterTracing/FinalOutcomeDataEvaluator.java
[KHP3-5560](https://thepalladiumgroup.atlassian.net/browse/KHP3-5560)
Date of outcome in the defaulter tracing outcome
[KHP3-5560]: https://thepalladiumgroup.atlassian.net/browse/KHP3-5560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updated Defaulter tracing register to align to template: Added Date of final outcome and renamed Last appointment date to Date of missed appointment

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pnc/PNCBloodPressureDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pnc/PNCPulseDataEvaluator.java
> Updated PNC register to include Pulse rate and Blood Pressure added on Triage form same visit as pnc

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/pnc/PNCBabyPostpartumVisitTimingDataEvaluator.java
> Updated Visit timing Baby concepts for 0-48 hours,3-6 weeks and more than 6 weeks: Used new concepts

- api/pom.xml
- distro/pom.xml
- install/pom.xml
- omod/pom.xml
- pom.xml
> Bumping to v19.0.0

- omod/src/main/resources/config.xml
Add global properties for location based user/patient filter
> Add global properties for location based user/patient filter

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/resources/messages.properties
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/account/NewAccountFragmentController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/account/ProviderDetailsFragmentController.java
- omod/src/main/webapp/fragments/account/newAccount.gsp
- omod/src/main/webapp/fragments/account/providerDetails.gsp
[Screencast from 19-06-2024 05:05:03 ALASIRI.webm](https://github.com/palladiumkenya/openmrs-module-kenyaemr/assets/1901372/1be2cc7e-db48-41b8-83ee-2298903acf78)
> Added provider license and provider license expiry date for SHA Health Care worker verification

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/nupi/DuplicateNUPICalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/nupi/DuplicateNUPIReportBuilder.java
- api/src/main/resources/content/kenyaemr.common.xml
> Added NUPI Duplicates report

- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
This PR optimizes loops in the care panels. We had some non-performant loops in the initial work.
> Optimize loops in the care panels

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/hiv/AppointmentsTrackerReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/HivConsultationDuringPeriodCohortDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/cohort/definition/evaluator/HivConsultationDuringPeriodCohortDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/PatientAppointmentScheduledDateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/art/PatientAppointmentTCADateDataDefinition.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/PatientAppointmentScheduledDateDateDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/PatientAppointmentTCADateDataEvaluator.java
- api/src/main/resources/content/kenyaemr.hiv.xml
…
Kindly review on the appropriateness of:
1. Report name
2. Columns: I have included- Names, Sex,CCC,DOB plus the ones for interest: Date scheduled and TCA
3. Do we need a excel template 
4. Any other
> Added Appointment tracker report : with date scheduled and appointment date given stored in patient_appointment table

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/surveillance/EligibleForIDSRFlagsCalculation.java
> KHP3-6241 on DMI surveillance: Reduce Polio flagging sensitivity by adding onset status as sudden requirement

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/nupi/DuplicateNUPIReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/nupi/FacilityDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/nupi/FacilityDataDefinition.java
Modified the NUPI Duplicates report to include VL columns and Facility names
> Modified the NUPI Duplicates report to include VL columns and Facility names

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/resources/AlignCaseManagerCaseRelationships.sql
- omod/src/main/resources/liquibase.xml
> Updated relationship_type case manager - case manager to case manager- case , Migrated all the misaligned cases in relationships

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/HTSTestSettingDataEvaluator.java
Add a column on Setting with options being Facility or Community. The column added but it is not populating
> The column added but it is not populating

- omod/src/main/resources/config.xml
Add global property to store exemptions configuration in KenyaEMR
> KHP3-6453: Add global property to store exemptions configuration in KenyaEMR

- api/pom.xml
- distro/pom.xml
- install/pom.xml
- omod/pom.xml
- pom.xml
> Bumping to v19.1.0

- pom.xml
> Aligning kenyaemrOrderentry version v1.6.5

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/EligibleForFastrackPatientsCalculation.java
- omod/src/main/resources/config.xml
- pom.xml
> Fix fast track form eligibility calculation to use appoitment from bahmni(Form was not showing)

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> Add metadata for specialized clinics

- omod/src/main/resources/liquibase.xml
Removing Facility status check scheduled tasks for optimization - will create a manual process for sync
> Removing Facility status check scheduled tasks for optimization - will create a manual process for sync

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/LastReturnVisitDateCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/LostToFollowUpCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/mchcs/PersonAddressCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/util/EmrUtils.java
This will help to make the code reusable in places where we need to use latest TCA date eg in `LastReturnVisitDateCalculation` and `LostToFollowUpCalculation`
> (refacotr): Refactor getting latest appointment date by service to Utils class

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
Added encounter and form uuid to support creation of special clinic maxillofacial
> maxillofacial form and encounter uuid creation

- api/src/main/resources/MigrateAppointmentsFromObs.sql
Reverts palladiumkenya/openmrs-module-kenyaemr#2007
> Revert "Remove date_created filter on the appointment migration query"

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/hts/PatientsEligibleForHtsScreeningCalculation.java
> Reduce hts eligibity screening age to start from 18 months and above

- api/pom.xml
- distro/pom.xml
- install/pom.xml
- omod/pom.xml
- pom.xml
> Bumping Kenyaemr to v19.1.2 to include bug fixes and some missing drugs

- api/src/main/java/org/openmrs/module/kenyaemr/task/AutoCloseActiveVisitsTask.java
This PR improves the existing logic by:
1. Target only open outpatient visits
2. Improve the visit search logic
> Limit visits to close to outpatient

- omod/src/main/resources/config.xml
Remove duplicate require module config for facility reporting
> Remove duplicate require module config for facility reporting

- api/src/main/java/org/openmrs/module/kenyaemr/EmrActivator.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
Adds a global property and a logic to save the version of installed KenyaEMR on startup
> save KenyaEMR version in a global property

- api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/EligibleForFamilyPlanningCalculation.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/resources/content/kenyaemr.common.xml
For some reason My IDE seems to have formatted common metadat file
> Enable family planning form to be shown

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
add metadata for diabetic clinic, encounter uuid and form uuid
> create metadata encounter uuid for diabetic clinic

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
This metadata has also been made available in the actual clinical form for ADR
> create metadata for adverse drug reaction form

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
- pom.xml
> Updating HIE Health Worker Registry endpoint changes and removing credentials from code - PR reviews

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> add metadata for hearing screening form

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
adding metadata for clinical forms on Morgue and Neurology
@makombe
> add neurology special clinic and morgue form metadata

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> add metadata for morgue module

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/MOH240LabReportBuilder.java
> Updated MOH240 to include OpenmrsID as opd clinic number and revisit number

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/MOH240LabReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/opd/OPDOrderingClinicianDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/opd/OPDRevisitsDataEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/opd/OPDRevisitsDataDefinition.java
> Updated MOH240 report for revisits and clinician columns

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/FacilityMetadata.java
Setup metadata for provider and facility attributes for claims processing
Ticket: KHP3-7310
This is a replacement of https://github.com/palladiumkenya/openmrs-config-kenyaemr/pull/990
> KHP3-7310: Setup metadata for provider, facility attributes for claims processing

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> Adding provider attributes : Qaulification,Address and telephone

- api/src/main/java/org/openmrs/module/kenyaemr/chore/AddCD11MappingCodeSetsForDiagnosis.java
- api/src/main/java/org/openmrs/module/kenyaemr/chore/AddICD11MappingCodeSetsForDiagnosis.java
1. Added a chore to incorporate ICD11 codesets to diagnosis class concepts
2. Validates that if a ICD11 mapping exists it does not duplicate
3. Added 5 diagnosis: 
- Headache,Malaria,Pneumonia,Typhoid and Fever
> Added a chore to incorporate ICD11 codesets to diagnosis class concepts

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> add metadata for infectious disease clinic

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> Remove duplicate metadata for partograph

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> Add metadata for plastic surgery clinic

- api/src/main/java/org/openmrs/module/kenyaemr/FacilityDashboardUtil.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
> Added endpoint to provide case surveillance indicators, denominators and threshhold

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/PublicHealthActionReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/publicHealthActionReport/PublicHealthActionCohortLibrary.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/publicHealthActionReport/PublicHealthActionIndicatorLibrary.java
1. Pregnant/postpartum women at high risk (ML-based) not linked to PrEP
2. Virally unsuppressed clients without Enhanced Adherence Counseling (EAC) within 2 weeks   : Done
3 . HEI (6-8 weeks) without DNA PCR results
4. HEI (24 months) without a final documented outcome
> Added Clinical action report 5 real time dashboard indicators

- api/src/main/java/org/openmrs/module/kenyaemr/util/EncounterBasedRegimenUtils.java
- api/src/main/resources/regimens.xml
file:///home/patrick/Pictures/Screenshots/Screenshot%20from%202025-03-11%2010-09-05.png
file:///home/patrick/Pictures/Screenshots/Screenshot%20from%202025-03-11%2010-38-33.png
> Adding TLD(TDF/3TC/DTG) for child second line regimen and TAF/3TC/DTG as second line regimen for adults

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/finacials/SetupFacilityMonthlyRevenueCollectionBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/finacials/FacilityRevenueSummaries.java
> Updated monthly revenue collection report - removed query returning blank columns

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
Added a new encounter type for IIT score
> Added a new encounter type for IIT score

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/HivMetadata.java
@makombe kindly review and merge
> alignment of GBV Metadata to read Violence Screening

- api/src/main/java/org/openmrs/module/kenyaemr/FacilityDashboardUtil.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
* Add start and end date filter for facility dashboard
> (feat) Add date filter param

- api/src/main/java/org/openmrs/module/kenyaemr/FacilityDashboardUtil.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
* Add Monthly hiv positive not linked line graph endpoint
> (feat) Add monthly Hiv positive not linked

- api/src/main/java/org/openmrs/module/kenyaemr/FacilityDashboardUtil.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
* Add Hiv positive not linked bar graph
> (feat) HIV not linked bar graph

- api/src/main/resources/metadata/mfl_2014-05-12.csv
Reverts palladiumkenya/openmrs-module-kenyaemr#2139
> Revert "Added 5 facilities to the KenyaEMR facility list"

- api/src/main/java/org/openmrs/module/kenyaemr/FacilityDashboardUtil.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
* Add Monthly high-risk PBFW not on PrEP line graph
> (feat) monthly high risk pbfw line graph

- api/src/main/java/org/openmrs/module/kenyaemr/FacilityDashboardUtil.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
* Add monthly delayed EAC
* Add Monthly VL missed opportunities
* Add Monthly DNA PCR pending
* Add Monthly HEI final outcome
> (feat) survey line graphs

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/ActiveInMchDataDefinitionEvaluator.java
Revise the Active in PMTCT column in the Active on ART Patients Linelist to show PMTCT mothers who are pregnant or breastfeeding.
Replace the current ‘Yes’ with either the mother is pregnant or Breastfeeding. If the mother is not active in PMTCT retain ‘No’.
> Revise the Active in PMTCT column in the Active on ART Patients Linelist

- api/src/main/java/org/openmrs/module/kenyaemr/dataExchange/FacilityStatusHandler.java
- api/src/main/java/org/openmrs/module/kenyaemr/dataExchange/SHABenefitsPackageHandler.java
- api/src/main/java/org/openmrs/module/kenyaemr/dataExchange/SHAInterventionsHandler.java
Made the SHA data files paths dynamic
> Made the SHA data files paths dynamic

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
@makombe kindly review and merge if without any issues
> add metadata for IPD discharge form

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> Added provider unique identifier as a provider attribute

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/shared/common/CommonDimensionLibrary.java
> Add missing age dimension for moh-745 affecting viewing of report

- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
> Added a try catch block around the SHAInterventionHandler for proper error handling

- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
> Reverting flags for patients enrolled on programs only to cater for facility wide clients

- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
This should allow us to use `visitUuid` to retrieve visit and check forms available for RDE 
[Kapture 2025-05-15 at 14.02.13.webm](https://github.com/user-attachments/assets/d9370b8c-45c1-4858-8b2b-0b69ba6f4ff4)
> (feat) : Update logic to show RDE forms to use simple `getVisitByUuid` method

- api/src/main/java/org/openmrs/module/kenyaemr/chore/UpdatePartographConceptsToAllowDecimals.java
> Update partograph form concepts to allow decimals

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
@makombe kindly review and merge if no issues
> add Leprosy clinic metadata

- api/src/main/java/org/openmrs/module/kenyaemr/FacilityDashboardUtil.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
* Add base indicator queries for surveillance dashboard stack bar graphs
> (feat): add base indicators for stack bars

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/sgbv/EmotionalIPVDataDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/sgbv/PhysicalIPVDataDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/sgbv/SexualIPVDataDefinitionEvaluator.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/ETLReports/RevisedDatim/DatimCohortLibrary.java
> Updated violence screening queries to include revised concepts in the form

- omod/src/main/resources/config.xml
> Made DMI flagging active by default : Turned config to true

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> add Fluid Intake form metadata

- omod/src/main/resources/config.xml
> Adding config for the claims callback endpoint url

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
@makombe kindly review. This PR will accord a user to see Emergency as a visit when they checkin a patient during a visit
> add Emergency/Casualty Department metadata

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/MohReportUtils/DiagnosisConcepts.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/MohReportUtils/DiagnosisLists.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/MOH705AReportBuilder.java
- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/MOH705BReportBuilder.java
> Aligned malaria concepts across MOH705A and MOH705B

- api/src/main/resources/content/kenyaemr.common.xml
> Updated the correct name for FCDRR MOH 730B report

- api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/common/SetupMOH706LabReportBuilder.java
> KHP3-7569:MOH 706 Blood count concept missmatch using FBC 1019 instead of Blood Count: 679

- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
Added endpoint to check if global param kenyaemr.sha.registration.number is set
> Added endpoint to check if global param kenyaemr.sha.registration.number is set

- api/src/main/java/org/openmrs/module/kenyaemr/api/KenyaEmrService.java
- api/src/main/java/org/openmrs/module/kenyaemr/api/impl/KenyaEmrServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
- omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
> Updated OTP SMS to use HIE IL Mediator OTP, switching using otp source global property: Adding national ID optional paramater

- api/src/main/java/org/openmrs/module/kenyaemr/api/impl/KenyaEmrServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
> Removed hardcoded client id and client secret for HIE IL mediator into global configurations

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/MchMetadata.java
> Change the name of CWC form

- api/src/main/java/org/openmrs/module/kenyaemr/metadata/NCDMetadata.java
@makombe @patryllus kindly review
> add metadata for NCD Discontinuation form
