api/src/main/java/org/openmrs/module/kenyaemr/EmrActivator.java, api/src/main/java/org/openmrs/module/kenyaemr/task/AutoCloseActiveVisitsTask.java, omod/src/main/resources/liquibase.xml
Fetch all visits haven't ended or been closed and close them on startup and using a scheduler
1. Autocloses on startup by default
2. Autocloses when the scheduler is set
=> Fetch all visits haven't ended or been closed and close them on startup and using a scheduler

api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/art/LastViralLoadResultCalculation.java, omod/src/main/webapp/pages/dialog/cohortDialog.gsp
Removed prefix copies/ml from lastViralLoadResult calculation and appended this to cohorDialog
This is meant to facilitate reuse of lastViralLoadResult  calculation without having to strip the copies/ml part
=> Removed prefix copies/ml from lastViralLoadResult calculation and appended this to cohorDialog

api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/HIVEnrollment.java, api/src/main/resources/content/kenyaemr.common.xml
TB screening and clinical encounter form should be dropped for HIV+ clients to avoid duplication of efforts
=> TB screening and clinical encounter form should be dropped for HIV+ 

api/src/main/resources/content/kenyaemr.common.xml, api/src/main/resources/content/kenyaemr.hiv.xml
TB screening and clinical encounter form should be dropped for clients enrolled in HIV program to avoid duplication of efforts
=> TB screening and clinical encounter form should be dropped for clients

api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
Updating max National ID number limit to 18 to factor NUPI verification from Aliens using it
=> Updating max National ID number limit to 18 to factor NUPI verification from Aliens  Tanzanians ahave max 14 digits using it

omod/src/main/webapp/resources/htmlforms/mchms/mchmsDelivery.html
Add a filed in the form to record if the mother was given ART prophylaxis in the ANC or during the delivery visit. The two variables to be included are:
- Mother issued with ART prophylaxis from ANC
- Mother issued with ART prophylaxis at maternity.
Acceptance criteria.
- Allow the user to record either ‘Y or N for the option of ‘Mother issued with ART prophylaxis at the maternity’ if mother tested positive at maternity else N/A if the mother was a known positive.
- Allow the user to record either ‘Y ' or ‘N’ for the option of ‘Mother issued with ART prophylaxis from ANC’ if the mother was a known positive at the time of getting to delivery else N/A if the mother’s HIV status was Negative or Unknown before the time of the delivery.
=> Add a field to record mother;s ART prophilaxis

omod/src/main/webapp/resources/htmlforms/mchms/mchmsDelivery.html
Auto-populate the section ' Testing done in the maternity' from the HIV testing section in the same Delivery form. The results in the ' Testing done in the maternity' should be auto-populated as per the results received once the HIV testing part as been filled in the same form i.e. Auto-populate positive or Negative if testing final results is either positive or Negative. Auto-populate Known positive if the client was known to be positive before delivery and Unknown if there was no test done.
=> Auto populate Testing done in maternity

api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/hiv/art/ViralLoadCategoriesCalculation.java
VL test for patients above 1000
VL test for Patients between 200 - 999. The patient has 376
VL test for a patient with VL of 65, between 50-199
=> Revision on VL Categories

omod/src/main/webapp/resources/htmlforms/hiv/cccDefaulterTracing.html
Enhance the defaulter tracing form by adding more features.
If the Final Outcome/True Status is either ‘Dead' or ‘Receiving ART from another clinic/Transferred’ add a message 'Complete the HIV Discontinuation form’ for the user to action.
If not contacted add a drop down showing Reason not contacted. The options should be Tracking ongoing, No locator information, Inaccurate locator information, Died, Calls not going through and Other. If other add a text area to specify.
=> Enhance the defaulter tracing form by adding more features.

omod/src/main/webapp/resources/htmlforms/hiv/cccDefaulterTracing.html
Enhance the defaulter tracing form by adding more features.
If the Final Outcome/True Status is either ‘Dead' or ‘Receiving ART from another clinic/Transferred’ add a bunner for 'Complete the HIV Discontinuation form’ for the user to action.
=> Add Complete the HIV Discontinuation from banner

api/src/main/java/org/openmrs/module/kenyaemr/calculation/library/tb/NeedsTbSputumTestCalculation.java
Align the Alerts - After screening for TB and the outcome is presumed TB, currently the alert is due for sputum this needs to be updated to Due for GeneXpert
=> Align the Alerts

omod/src/main/webapp/resources/htmlforms/mchms/mchmsAntenatalVisit.html
In the MCH Antenatal Visit form, retain the previous height recorded for clients aged above 19 years as the height will never change.
=> In the MCH Antenatal Visit form, retain the previous height recorded

api/src/main/resources/regimens.xml
Add RHZE as a regimen in the TB Regimen history for the children. Currently the regimen is lacking. The regimen should be added in the intensive phase (child) list.
=> Add RHZE as a regimen in the TB Regimen history for the children.

omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
I have removed the completed forms from the endpoint. The reason for this is that on o3, on launching the forms, we will only show the available forms on the `form dashboard`. To view completed forms, users will have to navigate to the visits tab and see all the forms they have filled out from that Tab. 
cc @CynthiaKamau @makombe @ojwanganto
=> (enhancement) Removed completed forms from the returned results in adoption to UI Changes

omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
**Issue Fixed:** The PR addresses a loading issue with the VMMC Discontinuation form in KenyaEMR 3.x. Previously, the form failed to load due to a problem in retrieving the formUuid.
**Root Cause:** The issue stemmed from an erroneous override of the formUuid by an appended formUuid value, which should have been the form name instead.
=> (fix) Update discontinuationFormName to correct value

api/src/main/java/org/openmrs/module/kenyaemr/EmrConstants.java, api/src/main/java/org/openmrs/module/kenyaemr/metadata/FacilityMetadata.java, omod/src/main/resources/config.xml
Controls wether to run or skip the sync for facilities based on the location list in the EMR
=> add configuration to control refresh of facility list on startup

api/src/main/java/org/openmrs/module/kenyaemr/util/EmrUtils.java, omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/VisitAvailableFormsFragmentController.java, omod/src/main/resources/config.xml
Adds exemption list for forms to access in 3.x
=> add exemption list for forms in 3.x

api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java, omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
=> Khp3 5332 nupi endpoint 3.x

omod/src/main/java/org/openmrs/module/kenyaemr/fragment/controller/patient/PatientUtilsFragmentController.java
This PR reverts a previous commit that adds a category of flags that should only be shown based on a user's role.
=> show all patient flags in 2.x based on eligibility criteria

api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
This PR add a new person attribute to support KDOD civilian runs. This is informed by KDOD request to customize the registration page,
```json
"Veteran",
"Dependant",
"MOD Civilian",
"DEFCO Civilian",
"UPHS Civilian",
"Other Civilian",
```
=> (feat) Add civilian categories for KDOD to match latest requirements

api/src/main/resources/apiCacheConfig.properties
This PR adds:
1. Config to keep cache for 3 hours i.e. 3600 x 3
2. Set overflow to disk if elements in cache are more than 1k
=> refined configs for ehcache

api/src/main/distro/metadata/identifierTypes.xml, api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
This PR address request from KDOD through @mmatheka and andreline to 
1. Update name for KDOD Service number to Service Number 
2. Add a new identifier .i.e `Publication Number` that uniquely identifies military dependents, aiding in organizing and linking them to service members
=> (feat) : update `KDOD Service Number` to `Service Number` & and add `Publication No`

omod/src/main/resources/liquibase.xml
Removed schedulers
===================
1. Facility status Task
2. Muzima Queue Data Processor Task
3. Medic Queue Data Processor Task
4. Push Contact list to Medic Mobile CHT system Task
5. Push positive clients pending linkage to Afyastat Task
6. Push Patient info to Vdot system Task
7. Pull Patient data from Vdot system Task 
8. Vdot Enrollment Queue Data Processor Task
9. Process Outbox Task Processor Task
10. Process Inbox Task 
11. HTS Contact Listing form processor Task
12. Queue positive clients pending linkage to Afyastat Task
13. Queue Contact list to Medic Mobile CHT system Task
14. Sync CCC numbers with CR Task 
15. Pull Mlab viral load results Task
=> Removing 15 flags for optimization - for Vdot, AfyaSTAT,Outbox,Inbox,Mlab and CR

api/src/main/resources/MigrateAppointmentsFromObs.sql
This filter was useful not to delete appointment created through o3 for the o3 sites when doing migration.( **We hope all o3 sites have now aligned )**
But for sites that are stilling using 2x i.e site which still fill next appointment date on green card and not using the appointment launcher. These sites still have the appointment sync feature running on the background creating appointments and with that date cap means same appointments will still be migrated when they are transitioning to o3 using the liquibase feature we added.
The fix here is that for new site upgrading to o3, we clear the appointment table and migrate all appointments a fresh from the obs table.
=> Remove date_created filter on the appointment migration query

omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
This PR adds the required caresetting parameter when querying the orders API. It resolves the below error:
`java.lang.IllegalArgumentException: CareSetting is required
at org.openmrs.api.impl.OrderServiceImpl.getOrders(OrderServiceImpl.java:560)`
=> add the missing caresetting when querying drug orders for TPT

omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
Disable flags for patients not enrolled in any program
=> Disable flags for patients not enrolled in any program

api/src/main/java/org/openmrs/module/kenyaemr/DwapiMetricsUtil.java, omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
DWAPI metrics endpoint will be available at `<host>/openmrs/ws/rest/v1/kenyaemr/getemrmetrics`
The response looks like the below:
`{
"EmrName": "KenyaEMR",
"EmrVersion": "19.1.2",
"LastLoginDate": "2024-Jul-26",
"LastMoH731RunDate": null
}
`
@andrineM @Murithijoshua @RAJABIBRAZ please note that we'll not need to include the psmart module in our releases.
=> Add Dwapi metrics endpoint from psmart module

api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/NCDDateDataEvaluator.java, api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/NCDSDataEvaluator.java, api/src/main/java/org/openmrs/module/kenyaemr/reporting/data/converter/definition/evaluator/art/NCDStatusDataEvaluator.java
Revise the NCD column in Active on ART to pick the most current HIV greencard
=> Revise the NCD column in Active on ART to pick the most current HIV greencard

api/pom.xml, distro/pom.xml, install/pom.xml, omod/pom.xml, pom.xml
=> (ci) : update to kenyacore 3.0.2-SNAPSHOT

api/src/main/java/org/openmrs/module/kenyaemr/metadata/MchMetadata.java
@makombe kindly review for me this
=> add metadata for MCH postnatal newborn examination form

api/src/main/java/org/openmrs/module/kenyaemr/metadata/CommonMetadata.java
There was a need to add the provider's passport number to support synchronization
=> (feat) Added provider attribute: passport number

api/src/main/java/org/openmrs/module/kenyaemr/reporting/library/MOH710/Moh710CohortLibrary.java
- This is due to the selection of two queries in the ETL.
=> Yellow fever vaccine when selected does error occurs

omod/src/main/java/org/openmrs/module/kenyaemr/web/controller/KenyaemrCoreRestController.java
Update the visit date handling in the backend so that all incoming visitStartDate and visitEndDate values strictly adhere to the OpenMRS ISO-8601 format (yyyy-MM-dd'T'HH:mm:ss.SSSZ)
=> (fix) : ensure visit date format follow OpenMRS supported formats

api/src/main/java/org/openmrs/module/kenyaemr/reporting/builder/stock/SetFcdrrReportBuilder.java
Fix the current disposal column.
Revert the drugs to display in the smallest units possible, i.e, tablets, not packets.
Remove the negative in negative adjustments and current disposal.
The opening balance is always added to the current received
=> Fcdrr update
